#!/bin/bash

PENTAHO_HOME=$HOME/Pentaho
echo "$PENTAHO_HOME"
#sh -c  "sed -i -e 's/IA4HCP/\"\/home\/pentaho\/Pentaho\"/g' auto-install.xml"
sh -c  "sed -i -e 's/IA4HCP/$PENTAHO_HOME/g' auto-install.xml"
#sh -c "sed -i -e '35s/^.*$/PGDATA=\"\/var\/lib\/pgsql\/data\"/g' /etc/init.d/postgresql"
